prd_paths:
  ArXiv_digest: "system/benchmark_data/python/ArXiv_digest/docs/PRD.md"
  chakin: "system/benchmark_data/python/chakin/PRD.md"
  geotext: "system/benchmark_data/python/geotext/PRD.md"
  hone: "system/benchmark_data/python/hone/docs/PRD.md"
  Hybrid_Images: "system/benchmark_data/python/Hybrid_Images/docs/PRD.md"
  lice: "system/benchmark_data/python/lice/PRD.md"
  particle-swarm-optimization: "system/benchmark_data/python/particle-swarm-optimization/docs/PRD.md"
  readtime: "system/benchmark_data/python/readtime/docs/PRD.md"
  stocktrends: "system/benchmark_data/python/stocktrends/docs/PRD.md"
  TextCNN: "system/benchmark_data/python/TextCNN/PRD.md"

tracker_v2:
  ArXiv_Digest: 1
  chakin: 1
  geotext: 1
  hone: 1
  Hybrid_Images: 1
  lice: 3 # changed the design prompt
  particle-swarm-optimization: 1
  readtime: 2 # changed the approve implementation prompt
  stocktrends: 1
  TextCNN: 1

tracker_v3:
  ArXiv_Digest: 1
  chakin: 2
  geotext: 1
  hone: 1
  Hybrid_Images: 4 # change the approve implementation prompt
  lice: 6 # change the approve implementation prompt with feedback message
  particle-swarm-optimization: 2 # had an error on unit test feedback string object doesn't have content attrib
  readtime: 1
  stocktrends: 1
  TextCNN: 1

tracker_v4:
  ArXiv_Digest: 1
  chakin: 1 # changed file saving issue not related to LLMs
  geotext: many # revised unit test and implementation prompt iterations
  hone: 2 # but issue with saving files / not related to LLMs
  Hybrid_Images: 1
  lice: 1 
  particle-swarm-optimization: 1
  readtime: 1
  stocktrends: 1 # had some issues with <<<<< HEAD in the benchmark PRD fixed file and reran
  TextCNN: 1


tracker_v5:
  ArXiv_Digest: 2
  chakin: 1
  geotext: 1
  hone: 2
  Hybrid_Images: 1
  lice: 1
  particle-swarm-optimization: 1
  readtime: 1
  stocktrends: 2
  TextCNN: 1